CREATE TABLE workout_plan
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier UUID,
    user_id    BIGINT,
    name       VARCHAR(255),
    active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_workout_plan PRIMARY KEY (id)
);

CREATE TABLE workout_plan_exercises
(
    workout_plan_entity_id BIGINT NOT NULL,
    exercises_id           BIGINT NOT NULL
);

ALTER TABLE workout_plan
    ADD CONSTRAINT FK_WORKOUT_PLAN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE workout_plan_exercises
    ADD CONSTRAINT fk_worplaexe_on_exercise_entity FOREIGN KEY (exercises_id) REFERENCES exercise (id);

ALTER TABLE workout_plan_exercises
    ADD CONSTRAINT fk_worplaexe_on_workout_plan_entity FOREIGN KEY (workout_plan_entity_id) REFERENCES workout_plan (id);